TRAIN:
  ENABLE: True
  DATASET: kdx
  BATCH_SIZE: 4
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: pretrained_ckpts/I3D_NLN_8x8_R50.pkl
  CHECKPOINT_TYPE: caffe2
DATA:
  PATH_TO_DATA_DIR: data
  PATH_PREFIX: data/resized_rgb320
  SAMPLING: 0
  NUM_FRAMES: 8
  SAMPLING_RATE: 8
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3], [4], [6], [3]]
NONLOCAL:
  LOCATION: [[[]], [[1, 3]], [[1, 3, 5]], [[]]]
  GROUP: [[1], [1], [1], [1]]
  INSTANTIATION: softmax
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 1e-5
  MAX_EPOCH: 70
  LR_POLICY: none
  WEIGHT_DECAY: 1e-6
  WARMUP_EPOCHS: 0.0
  WARMUP_START_LR: 1e-6
  OPTIMIZING_METHOD: adam
MODEL:
  NUM_CLASSES: 400
  ARCH: i3d
  MODEL_NAME: ResNet
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
