DATA:
  TEST_CROP_SIZE: 255
TEST:
  ENABLE: True
  DATASET: kdx
  BATCH_SIZE: 16
  NUM_ENSEMBLE_VIEWS: 5
  NUM_SPATIAL_CROPS: 3
  ENSEMBLE_METHOD: sum
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: False
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
